name: "âš™ï¸ CI Feature Branch"

on:
  push:
    branches:
      - feature**
      - '[0-9].[0-9].x'
      - 'v[0-9].[0-9].[0-9]'
      - 'v[0-9].[0-9].x'
      - docs**

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  ci-terraform-dynamodb-table:
    name: ðŸ› ï¸ ci-terraform-dynamodb-table
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init
        working-directory: aws/dynamodb-table

      - name: Terraform Validate
        run: terraform validate
        working-directory: aws/dynamodb-table
  
  ci-terraform-iam-role:
    name: ðŸ› ï¸ ci-terraform-iam-role
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init
        working-directory: aws/iam-role

      - name: Terraform Validate
        run: terraform validate
        working-directory: aws/iam-role
  
  ci-terraform-lambda-layer:
    name: ðŸ› ï¸ ci-terraform-lambda-layer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init
        working-directory: aws/lambda-layer

      - name: Terraform Validate
        run: terraform validate
        working-directory: aws/lambda-layer
  
  ci-terraform-sqs-queue:
    name: ðŸ› ï¸ ci-terraform-sqs-queue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: Terraform Init
        run: terraform init
        working-directory: aws/sqs-queue

      - name: Terraform Validate
        run: terraform validate
        working-directory: aws/sqs-queue

  open-pr-to-main:
    name: ðŸ”“ open-pr-to-main
    runs-on: ubuntu-latest
    needs:
      - ci-terraform-dynamodb-table
      - ci-terraform-iam-role
      - ci-terraform-lambda-layer
      - ci-terraform-sqs-queue

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ðŸ”“ PR to main
        uses: peter-evans/create-pull-request@v7
        with:
          base: main
          branch: ${{ github.ref }}
          title: "pr(main): ${{ github.ref }} -> main"
          body-path: ".github/pull_request_template.md"
          labels: "github-bot ðŸ¤–"
          commit-message: "bot: automatic PR opening to main branch"
          
