name: "ğŸš€ CI Terraform Module Releaser"

on:
  pull_request:
    types: [opened, reopened, synchronize, closed] # Closed required
    branches:
      - main

permissions:
  contents: write # Required for to push tags, create release, and push changes to the wiki
  pull-requests: write # Required to comment on pull request

jobs:
  ci-terraform-dynamodb-table:
    name: ğŸ› ï¸ ci-terraform-dynamodb-table
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@v4

      - name: â›ï¸ Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: ğŸƒ Terraform Init
        run: terraform init
        working-directory: aws/dynamodb-table

      - name: âœ… Terraform Validate
        run: terraform validate
        working-directory: aws/dynamodb-table
  
  ci-terraform-iam-role:
    name: ğŸ› ï¸ ci-terraform-iam-role
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@v4

      - name: â›ï¸ Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: ğŸƒ Terraform Init
        run: terraform init
        working-directory: aws/iam-role

      - name: âœ… Terraform Validate
        run: terraform validate
        working-directory: aws/iam-role
  
  ci-terraform-lambda-layer:
    name: ğŸ› ï¸ ci-terraform-lambda-layer
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@v4

      - name: â›ï¸ Terraform Setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.5

      - name: ğŸƒ Terraform Init
        run: terraform init
        working-directory: aws/lambda-layer

      - name: âœ… Terraform Validate
        run: terraform validate
        working-directory: aws/lambda-layer

  release:
    name: ğŸš€ terraform-module-releaser
    runs-on: ubuntu-latest
    needs:
      - ci-terraform-dynamodb-table
      - ci-terraform-iam-role
      - ci-terraform-lambda-layer
    
    steps:
      - name: ğŸ”„ Checkout
        uses: actions/checkout@v4

      - name: ğŸš€ Terraform Module Releaser
        uses: techpivot/terraform-module-releaser@v1.4.1
        with:
            default-first-tag: v0.0.1
            major-keywords: major change,breaking change
            minor-keywords: feat,feature
            patch-keywords: fix,hotfix,chore,docs,config,ci
            terraform-docs-version: v0.19.0